[package]
name = "itask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
itertools = "0.13.0"
ratatui = { version = "0.28.1", features = ["unstable-widget-ref"] }
tiny-gradient = "0.1.0"
tokio = { version = "1.40.0", features = ["full"] }
